<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Website orders (المسار الجديد بدون تسجيل دخول): a visitor completes the
 * create-contract wizard and submits their WhatsApp number. The site's server
 * route (/api/order) POSTs the order here so it is stored as the source of
 * truth, independent of the Telegram / email notification channels.
 *
 * NOTE: named `website_orders` on purpose — in this system "orders" in the
 * dashboard already means contract requests (Contracts module). These are the
 * new no-login website submissions, a distinct concept.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('website_orders')) {
            return;
        }

        Schema::create('website_orders', function (Blueprint $table) {
            $table->id();
            // Human-facing order number generated by the website (e.g. AQ-260925-4821). Unique.
            $table->string('order_number')->unique();
            $table->string('contract_type')->nullable();
            $table->string('whatsapp_number')->nullable()->index();
            // Display-ready order details as sent by the site: [{ title, fields: [{ label, value }] }].
            $table->json('sections')->nullable();
            $table->text('notes')->nullable();
            $table->string('source')->nullable();
            // new = just received; the dashboard moves it forward (contacted / done).
            $table->string('status')->default('new')->index();
            $table->timestamp('submitted_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('website_orders');
    }
};
